apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: golang-api

build:
  artifacts:
    - image: amitkuamrdube/golang-api-skaffold
      context: .
      docker:
        dockerfile: Dockerfile
        noCache: false
        squash: false